### ISSUE TITLE
NullReferenceException in ActiveHandlerTrackingEntry with 2.2.0 preview 3

### ISSUE THREAD

**Issue by martincostello** [aspnet/HttpClientFactory#194]
I don't yet have a repro, but I've just updated an ASP.NET Core web app that uses IHttpClientFactory to 2.2.0 preview 3, and I've got some in-memory self-hosted tests failing because of the following exception causing `dotnet test` to terminate:

```
[18:18:48][dotnet test] The active test run was aborted. Reason: Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[18:18:48][dotnet test]    at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
[18:18:48][dotnet test]    at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.<>c.<.cctor>b__22_0(Object s)
[18:18:48][dotnet test]    at System.Threading.TimerQueueTimer.CallCallback()
[18:18:48][dotnet test]    at System.Threading.TimerQueueTimer.Fire()
[18:18:48][dotnet test]    at System.Threading.TimerQueue.FireNextTimers()
[18:18:48][dotnet test]    at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

I guess that one of either `_timer` or `_callback` is somehow `null`:

https://github.com/aspnet/HttpClientFactory/blob/5255a24fe5bc5585e6fda2abaf78ae75936fa30b/src/Microsoft.Extensions.Http/ActiveHandlerTrackingEntry.cs#L75-L87

**Comment by martincostello** [comment]
It's also not a one-off, as we run these tests in batches based on categories to get some parallelism across TeamCity jobs, and 4 different jobs (of 7) have all failed with the same exception.

**Comment by rynowak** [comment]
Ah yes. It's probably the case that we need to null check the timer when we access it. This was a 2.2.0 change.

**Comment by palmtech** [comment]
Is there any workaround for this? All of our preview 3 containers terminate every few minutes with this error.

**Comment by martincostello** [comment]
Looking at the code, I think the only workaround is to make the messsge handler lifetimes either Infinite or really long (~the usual lifetime of your containers).

**Comment by rynowak** [comment]
Fixed this for 2.2 - sorry I don't think there's a workaround here. This is just broken. What happens is that an additional timer is started each time you request an HTTP client within the lifetime of a single handler.

**Comment by palmtech** [comment]
Ok, might be worth adding it to the known issues. Preview 3 is probably a skip for most microservice-ish apps.

**Comment by rynowak** [comment]
Yeah that's a fair point, will do.

**Comment by rynowak** [comment]
Added https://github.com/aspnet/Announcements/issues/323
